// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(PlantDetailContext))]
    [Migration("20200530195008_Popravak")]
    partial class Popravak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.PlantDetail", b =>
                {
                    b.Property<int>("PMid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Maxtemp");

                    b.Property<string>("Maxwater")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Mintemp");

                    b.Property<string>("Minwater")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("PMid");

                    b.ToTable("PlantDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
