// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(PlantDetailContext))]
    partial class PlantDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.PlantDetail", b =>
                {
                    b.Property<int>("PMid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Maxtemp");

                    b.Property<int>("Maxwater");

                    b.Property<int>("Mintemp");

                    b.Property<int>("Minwater");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("PMid");

                    b.ToTable("PlantDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
